### ISSUE TITLE
setup

### ISSUE THREAD

**Issue by carriewright11** [SISBID/Module1#134]
accidentally have something about all the packages apparently:

The following file is not found in the "This file" link (https://jhudatascience.org/intro_to_r/resources/all_the_packages.txt) of the R and RStudio Installation html page.

**Comment by carriewright11** [comment]
Also might want to update new file names to be slightly more consistent - was working quickly

**Comment by carriewright11** [comment]
I don't think this is in there now...

**Comment by carriewright11** [comment]
@avahoffman am I just not seeing this? do you see it?

**Comment by avahoffman** [comment]
Yeah I think this is resolved!
