### ISSUE TITLE
general thought

### ISSUE THREAD

**Issue by carriewright11** [SISBID/Module1#172]
I really like how we have a part 1 and part2 in some cases of simple and then more advanced - I feel like that is really helpful for having a mix of people - they know when to especially tune in for what is more appropriate for them. I wonder if we want to think about that for intro to R/ DaSEH

**Comment by carriewright11** [comment]
What do you think @avahoffman ?

**Comment by avahoffman** [comment]
Yeah I like that Idea - maybe close the issue here and make one in [daseh](https://github.com/fhdsl/daseh) ?
