### ISSUE TITLE
Data IO part 2 lab

### ISSUE THREAD

**Issue by carriewright11** [SISBID/Module1#173]
need to add this back for question 5 and 6: https://sisbid.github.io/Data-Wrangling/data/iris/iris_q6.xlsx

**Comment by carriewright11** [comment]
maybe the full thing: curl::curl_download("https://sisbid.github.io/Data-Wrangling/data/iris/iris_q6.xlsx", "iris_q6.xlsx")

**Comment by avahoffman** [comment]
haha I feel so dumb 🙈

**Comment by carriewright11** [comment]
> haha I feel so dumb 🙈

We all do it! No worries :)
