### ISSUE TITLE
Bug with `SummarizedExperiment`

### ISSUE THREAD

**Issue by avahoffman** [SISBID/Module1#64]
https://github.com/SISBID/Data-Wrangling/blob/d140e02b0bbb55199dbcaab8759f1e6c718c9df8/lecture_notes/Bioconductor_intro.Rmd#L214

Appears to be a bug here. @carriewright11 you mentioned a problem others might be having - could we link to it here?

**Comment by carriewright11** [comment]
I think this is it... https://github.com/hansenlab/bsseq/issues/95 I tried modifying the code and maybe made it worse :P not sure

**Comment by carriewright11** [comment]
Was a great idea to put the link here! Thanks for making this issue

**Comment by carriewright11** [comment]
we don't need to worry about this one for now :) Since we plan to move in a GitHub direction

**Comment by avahoffman** [comment]
I think we can close this since we are taking out Bioconductor! @carriewright11
