### ISSUE TITLE
Filtering for "4" when it's in a character type column

### ISSUE THREAD

**Issue by avahoffman** [SISBID/Module1#81]
In the subsetting lab part 1:

```
mpg %>% filter(displ > 4 & drv == 4)
mpg %>% filter(displ > 4 & drv == "4")
```

Both of these yield the same results. Might be worth some explanation that as numbers can be quoted or not, regardless of the column data class

**Comment by carriewright11** [comment]
a bit worried that this might encourage:
 diamonds %>% filter(price > "3000") which doesn't work.
